# Generated by Django 5.2.7 on 2025-12-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ad_budget_ad_category_ad_end_date_ad_hours_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
