from django.urls import path
from .views import (
    AdListCreateView,
    AdDetailView,
    ProposalListCreateView,
    ProposalAcceptView,
    ProposalCompleteView,
    ProposalConfirmCompletionView,
    ProposalDetailView,
    AdCommentsListCreateView,
    CommentDetailView,
    RatingListCreateView,
    TicketListCreateView,
    TicketDetailView,
    TicketMessageListCreateView,
    ScheduleListCreateView,
    ScheduleDetailView,
    ContractorProfileView,
    ContractorListView,
    CustomerProfileView,
    UserRoleUpdateView,
)

urlpatterns = [
    path('ads/', AdListCreateView.as_view(), name='ad-list-create'),
    path('ads/<int:pk>/', AdDetailView.as_view(), name='ad-detail'),
    path('proposals/', ProposalListCreateView.as_view(), name='proposal-list-create'),
    path('proposals/<int:pk>/', ProposalDetailView.as_view(), name='proposal-detail'),
    path('proposals/<int:pk>/accept/', ProposalAcceptView.as_view(), name='proposal-accept'),
    path('ads/<int:ad_id>/comments/', AdCommentsListCreateView.as_view(), name='ad-comments-list-create'),
    path('comments/<int:pk>/', CommentDetailView.as_view(), name='comment-detail'),
    path('contractors/<int:contractor_id>/ratings/', RatingListCreateView.as_view(), name='contractor-ratings-list-create'),
    path('ratings/', RatingListCreateView.as_view(), name='ratings-list-create'),
    path('tickets/', TicketListCreateView.as_view(), name='tickets-list-create'),
    path('tickets/<int:pk>/', TicketDetailView.as_view(), name='ticket-detail'),
    path('tickets/<int:ticket_id>/messages/', TicketMessageListCreateView.as_view(), name='ticket-messages'),
    path('contractors/<int:contractor_id>/schedule/', ScheduleListCreateView.as_view(), name='contractor-schedule-list-create'),
    path('schedules/<int:pk>/', ScheduleDetailView.as_view(), name='schedule-detail'),
    path('proposals/<int:pk>/complete/', ProposalCompleteView.as_view(), name='proposal-complete'),
    path('proposals/<int:pk>/confirm/', ProposalConfirmCompletionView.as_view(), name='proposal-confirm'),
    path('contractors/<int:pk>/profile/', ContractorProfileView.as_view(), name='contractor-profile'),
    path('customers/<int:pk>/profile/', CustomerProfileView.as_view(), name='customer-profile'),
    path('contractors/', ContractorListView.as_view(), name='contractor-list'),
    path('users/<int:pk>/role/', UserRoleUpdateView.as_view(), name='user-role-update'),
]
